/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnetionsConnectionIdRouteImport } from './routes/connetions.$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnetionsConnectionIdRoute = ConnetionsConnectionIdRouteImport.update({
  id: '/connetions/$connectionId',
  path: '/connetions/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connetions/$connectionId': typeof ConnetionsConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connetions/$connectionId': typeof ConnetionsConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connetions/$connectionId': typeof ConnetionsConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connetions/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connetions/$connectionId'
  id: '__root__' | '/' | '/connetions/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnetionsConnectionIdRoute: typeof ConnetionsConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connetions/$connectionId': {
      id: '/connetions/$connectionId'
      path: '/connetions/$connectionId'
      fullPath: '/connetions/$connectionId'
      preLoaderRoute: typeof ConnetionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnetionsConnectionIdRoute: ConnetionsConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
